### PR TITLE
Adds support for abstract and final modifiers

### PR DESCRIPTION
**Pull request by doublecompile**
This pull request adds support for identifying:

* The `async` modifier on functions and methods
* The `abstract` modifier on classes and methods
* The `final` modifier on classes and methods

New constructor arguments are optional. This change set should be backward compatible.

Unit tests included.

### CODE REVIEW

**Comment by fredemmott** [comment]
Why do you care about async? This is usually irrelevant - what matters is that the return type is `Awaitable<T>`

**Comment by fredemmott** [comment]
https://docs.hhvm.com/hack/async/async-vs-awaitable

**Comment by fredemmott** [comment]
I'm a strong believer in bool values being bad long-term except for when they're obvious from the context (eg `setEnabled(false)`), especially when there's multiple. It's verbose, but usually the best way is to avoid this is separate enums - eg IS_ABSTRACT vs NOT_ABSTRACT, IS_FINAL vs NOT_FINAL. For methods it could be NORMAL | ABSTRACT | FINAL, but that's not workable for classes so separate enums are probably better for consistency.

**Comment by doublecompile** [comment]
@fredemmott As for why I care about the async modifier (and the others added in this pull request), I'm using definition-finder to generate API docs (see [hphpdoc](https://github.com/appertly/hphpdoc)), and I'd like the documentation generated to accurately reflect the declaring symbols.

As for bools vs enums, I'm up for any discussion you may have about the final API.

**Comment by fredemmott** [comment]
IMO it doesn't belong in API docs: if I have an async function, I can replace it with a non-async function returning the same Awaitable type with absolutely no change to callers or behavior, so it isn't part of the API, it's an implementation detail.

**Comment by fredemmott** [comment]
Also, really happy to see hphpdoc - we were hoping to split out the relevant parts of https://github.com/hhvm/user-documentation to a separate tool, but never had the time.

**Comment by fredemmott** [comment]
^ That's also why 'async' is not specified on any API references on docs.hhvm.com

**Comment by doublecompile** [comment]
Heh. Immediately after I commented, I started thinking about async. You're right — the fact that calling code is going to have to either `join` or `await` the `Awaitable` is what's important, so knowing the function/method has the `async` modifier is superfluous.

I can push a replacement commit removing the async additions, but how would you like to proceed on the `final` and `abstract` modifiers?

**Comment by fredemmott** [comment]
enums please

**Comment by doublecompile** [comment]
Okay. 
* I've removed the `async` stuff.
* We've now got an `AbstractnessToken` and a `FinalityToken` in the builders and consumers. The definitions now test for equality against the enums.

As a side note, the `static` boolean now seems like an outlier. Should I add in a `StaticityToken` and replace the consuming of the static token?

**Comment by fredemmott** [comment]
That would be great, thanks :)

**Comment by doublecompile** [comment]
`bool $static` → `StaticityToken $staticity` :+1: 

Because the constructor arguments have changed, this *may* constitute a backward compatibility break in keeping with semantic versioning. This of course depends on your opinion concerning what part of `definition-finder`'s API is public.

**Pull request merged**
